// Ported from the NORCET CBT reference prototype (web-test-screen) — same 100-question
// nursing paper, 5 sections of 20 questions, 18-minute per-section timers (90 min total).

export const QUESTIONS = [
  // ── Section A — Nursing Foundations (Q1–Q20) ──
  { text: "Study the 12-lead ECG tracing below carefully (drag/scroll to view all leads). Based on the rhythm and waveform characteristics, identify the most appropriate immediate nursing action.",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/12leadECG.jpg", imageLarge: true,
    options: ["Prepare for immediate defibrillation", "Document as Normal Sinus Rhythm and continue monitoring", "Administer IV Atropine as prescribed", "Elevate head of bed and administer O2"], answer: 1 },
  { text: "The best method to prevent hospital-acquired infection is:", options: ["Hand hygiene", "Bed making", "Patient counselling", "Early discharge"], answer: 0 },
  { text: "The first step in the nursing process is:", options: ["Planning", "Implementation", "Assessment", "Evaluation"], answer: 2 },
  { text: "The purpose of informed consent is to:", options: ["Reduce nursing workload", "Protect patient autonomy", "Increase bed occupancy", "Avoid documentation"], answer: 1 },
  { text: "Normal adult respiratory rate (breaths per minute) is:", options: ["8–12", "12–20", "22–28", "30–40"], answer: 1 },
  { text: "Which of the following is the correct duration for a surgical hand scrub?", options: ["1 minute", "2–3 minutes", "3–5 minutes", "10 minutes"], answer: 2 },
  { text: "Maslow's hierarchy places which of the following at the base (most basic level)?", options: ["Safety needs", "Self-actualisation", "Physiological needs", "Esteem needs"], answer: 2 },
  { text: "Normal adult systolic blood pressure range (mmHg) is:", options: ["60–80", "90–100", "100–140", "150–180"], answer: 2 },
  { text: "The correct position for a patient in hypovolaemic shock (while awaiting IV access) is:", options: ["High Fowler's", "Prone", "Modified Trendelenburg (legs elevated)", "Left lateral"], answer: 2 },
  { text: "The Glasgow Coma Scale (GCS) maximum score is:", options: ["10", "12", "15", "18"], answer: 2 },
  { text: "Normal urine output in an adult is approximately:", options: ["10–20 mL/hr", "30–50 mL/hr", "80–100 mL/hr", "120–150 mL/hr"], answer: 1 },
  { text: "Examine the chest X-ray image shown below. Which clinical finding is most consistent with this radiograph?",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Chest_X-ray_PA_3-8-2010.png",
    options: ["Tension pneumothorax", "Bilateral pleural effusion", "Normal chest X-ray", "Cardiomegaly with pulmonary oedema"], answer: 2 },
  { text: "Which of the following is a sign of infection at a surgical wound site?", options: ["Serous drainage", "Approximated wound edges", "Localised warmth, redness and purulent discharge", "Slight oedema on day 1"], answer: 2 },
  { text: "Which electrolyte is the PRIMARY intracellular cation?", options: ["Sodium (Na+)", "Calcium (Ca2+)", "Potassium (K+)", "Magnesium (Mg2+)"], answer: 2 },
  { text: "A patient rates pain as 8/10 on the Numeric Rating Scale. This indicates:", options: ["Mild pain", "Moderate pain", "Severe pain", "No pain"], answer: 2 },
  { text: "Which of the following actions VIOLATES aseptic technique?", options: ["Opening sterile packages towards yourself", "Keeping the sterile field above waist level", "Treating the outer inch of a sterile drape as contaminated", "Avoiding reaching across a sterile field"], answer: 0 },
  { text: "Which nursing diagnosis is written correctly in NANDA format?", options: ["Fever related to infection", "Fluid volume deficit related to vomiting as evidenced by dry mucous membranes", "Patient is dehydrated", "Dehydration due to poor intake"], answer: 1 },
  { text: "The primary purpose of nursing documentation is:", options: ["Legal protection only", "Communication, continuity of care, legal protection, and quality assurance", "Fulfilling hospital formality", "Billing purposes only"], answer: 1 },
  { text: "The ethical principle of 'do no harm' is referred to as:", options: ["Beneficence", "Justice", "Non-maleficence", "Autonomy"], answer: 2 },
  { text: "A nurse preparing to administer medication should verify the 'Five Rights'. Which of the following is NOT one of them?", options: ["Right patient", "Right dose", "Right diagnosis", "Right route"], answer: 2 },

  // ── Section B — Medical Surgical Nursing (Q21–Q40) ──
  { text: "Which vital sign is most critical to monitor in a patient in circulatory shock?", options: ["Temperature", "Blood pressure", "Respiration depth", "Pain score"], answer: 1 },
  { text: "Normal adult resting pulse rate (beats per minute) is:", options: ["40–50", "60–100", "110–130", "140–160"], answer: 1 },
  { text: "Which IV solution is isotonic and used for acute volume replacement?", options: ["0.9% Normal Saline", "Distilled water", "3% Hypertonic Saline", "50% Dextrose"], answer: 0 },
  { text: "Which position is most appropriate for a patient in acute respiratory distress?", options: ["Prone", "Supine", "High Fowler's (90°)", "Left lateral"], answer: 2 },
  { text: "The most common early complication after major abdominal surgery is:", options: ["Wound dehiscence", "Deep vein thrombosis", "Paralytic ileus", "Pulmonary embolism"], answer: 2 },
  { text: "First nursing action for a patient with suspected acute myocardial infarction is:", options: ["Administer aspirin immediately", "Obtain 12-lead ECG", "Call the physician", "Ensure patent airway, administer O2, and establish IV access"], answer: 3 },
  { text: "A diabetic patient shows trembling, diaphoresis and confusion. The nurse should FIRST:", options: ["Administer insulin", "Check blood glucose level", "Call the doctor", "Give IV dextrose immediately without checking"], answer: 1 },
  { text: "Which insulin type has the FASTEST onset of action?", options: ["NPH insulin", "Glargine (Lantus)", "Regular (soluble) insulin", "Lispro (Humalog)"], answer: 3 },
  { text: "The most common complication of prolonged immobilisation is:", options: ["Hypertension", "Pressure ulcer", "Hyperthyroidism", "Polycythaemia"], answer: 1 },
  { text: "The antidote for heparin overdose is:", options: ["Vitamin K", "Protamine sulphate", "Naloxone", "Flumazenil"], answer: 1 },
  { text: "Normal serum potassium level (mEq/L) is:", options: ["1.5–2.5", "3.5–5.0", "6.0–7.5", "8.0–10.0"], answer: 1 },
  { text: "The preferred site for intramuscular injection in adults is:", options: ["Deltoid", "Ventrogluteal", "Dorsogluteal", "Rectus femoris"], answer: 1 },
  { text: "A patient with COPD should receive supplemental oxygen at:", options: ["1–2 L/min via nasal cannula", "6–8 L/min via face mask", "10 L/min via non-rebreather mask", "15 L/min via Venturi mask"], answer: 0 },
  { text: "Which dressing is recommended for a Stage II pressure ulcer with minimal exudate?", options: ["Dry gauze", "Hydrocolloid dressing", "Alginate dressing", "Wet-to-dry dressing"], answer: 1 },
  { text: "Post-mastectomy arm care includes which of the following?", options: ["Taking blood pressure on the affected arm", "Wearing tight-fitting jewellery on the affected arm", "Avoiding venipuncture on the affected arm", "Using the affected arm for IV infusion"], answer: 2 },
  { text: "A classic sign of fluid overload is:", options: ["Dry mucous membranes", "Poor skin turgor", "Bibasal crackles on auscultation and pitting oedema", "Dark concentrated urine"], answer: 2 },
  { text: "A patient with chronic renal failure shows peaked T-waves on ECG. The nurse suspects:", options: ["Hypokalaemia", "Hyperkalaemia", "Hyponatraemia", "Hypernatraemia"], answer: 1 },
  { text: "Which of the following is NOT a sign of respiratory distress?", options: ["Nasal flaring", "Intercostal retractions", "SpO2 of 99% on room air", "Use of accessory muscles"], answer: 2 },
  { text: "Pre-operative teaching should include:", options: ["Post-operative turning, coughing and deep-breathing exercises", "Guaranteeing a successful outcome", "Discouraging patient questions", "Withholding information about possible complications"], answer: 0 },
  { text: "After Foley catheter insertion, the balloon should be inflated with:", options: ["Air", "Normal saline", "Sterile water as per manufacturer's instruction", "Distilled water mixed with antibiotic"], answer: 2 },

  // ── Section C — Child Health Nursing (Q41–Q60) ──
  { text: "Normal birth weight of a full-term neonate is:", options: ["1.5–2.0 kg", "2.5–4.0 kg", "4.5–5.5 kg", "5.5–6.5 kg"], answer: 1 },
  { text: "An Apgar score of 7–10 at 5 minutes indicates:", options: ["Severe birth asphyxia requiring resuscitation", "Moderate asphyxia", "Good condition — routine care required", "Stillbirth"], answer: 2 },
  { text: "BCG vaccine is administered at:", options: ["6 weeks of age", "At birth", "9 months", "18 months"], answer: 1 },
  { text: "The anterior fontanelle normally closes by:", options: ["3–6 months", "6–9 months", "12–18 months", "24–30 months"], answer: 2 },
  { text: "Which of the following is an advantage of breastfeeding over formula?", options: ["Easier to measure intake", "More convenient for working mothers", "Provides maternal antibodies (secretory IgA)", "Higher caloric density"], answer: 2 },
  { text: "Projectile vomiting shortly after feeding in a 3-week-old infant most likely suggests:", options: ["Gastroesophageal reflux", "Pyloric stenosis", "Intussusception", "Hirschsprung disease"], answer: 1 },
  { text: "Normal resting respiratory rate for a newborn (breaths per minute) is:", options: ["10–15", "20–30", "30–60", "70–90"], answer: 2 },
  { text: "Clark's rule for paediatric dosage calculation uses:", options: ["Child's age in years", "Child's weight in pounds (lbs)", "Child's height in cm", "Child's body surface area in m2"], answer: 1 },
  { text: "WHO reduced-osmolarity ORS contains sodium at a concentration of:", options: ["45 mmol/L", "75 mmol/L", "90 mmol/L", "120 mmol/L"], answer: 1 },
  { text: "Koplik's spots on the buccal mucosa are pathognomonic of:", options: ["Chickenpox", "Mumps", "Measles (Rubeola)", "Rubella"], answer: 2 },
  { text: "Normal haemoglobin level in a newborn (g/dL) is:", options: ["8–10", "11–13", "14–20", "21–25"], answer: 2 },
  { text: "A child presents with fever, severe headache, photophobia and neck stiffness. The nurse should first suspect:", options: ["Encephalitis", "Bacterial meningitis", "Migraine", "Febrile seizure"], answer: 1 },
  { text: "Normal heart rate for an infant (0–12 months) in beats per minute is:", options: ["60–80", "80–100", "100–160", "170–200"], answer: 2 },
  { text: "Growth monitoring in children is best performed using:", options: ["Chest circumference only", "Head circumference only", "Standardised growth charts (weight-for-age / height-for-age)", "Blood glucose level"], answer: 2 },
  { text: "Which of the following is a DANGER sign in a newborn requiring immediate referral?", options: ["Physiological jaundice on day 3", "Mild breast engorgement", "Inability to feed / poor suckling", "Slight moulding of head"], answer: 2 },
  { text: "DPT vaccine (first dose) is given at:", options: ["Birth", "6 weeks of age", "9 months", "12 months"], answer: 1 },
  { text: "The Moro (startle) reflex in a healthy neonate should disappear by:", options: ["1 month", "2 months", "3–4 months", "6 months"], answer: 2 },
  { text: "Which of the following is NOT a component of IMNCI classification?", options: ["Assess and classify", "Treat and counsel", "Follow up", "Surgical referral for all sick children"], answer: 3 },
  { text: "The most reliable site for measuring core temperature in a small infant is:", options: ["Axilla", "Oral", "Rectum", "Skin (forehead)"], answer: 2 },
  { text: "A sterile field is contaminated when:", options: ["It is kept dry throughout", "The outer border (1 inch) is treated as clean", "It falls below waist level", "It is opened immediately before use"], answer: 2 },

  // ── Section D — Community Health / Mental Health (Q61–Q80) ──
  { text: "The PRIMARY level of health care is provided at:", options: ["District hospital", "Medical college hospital", "Community health centre (CHC)", "Sub-centre / primary health centre (PHC)"], answer: 3 },
  { text: "Which of the following is a notifiable disease in India?", options: ["Common cold", "Chickenpox", "Cholera", "Hypertension"], answer: 2 },
  { text: "The cold chain in immunisation is maintained between:", options: ["+2°C to +8°C", "−10°C to −20°C", "0°C to +4°C", "+15°C to +25°C"], answer: 0 },
  { text: "DOTS (Directly Observed Treatment, Short-course) is used for treatment of:", options: ["Malaria", "Tuberculosis", "HIV/AIDS", "Leprosy"], answer: 1 },
  { text: "Epidemiology is the study of:", options: ["Body organ structure", "Distribution and determinants of disease in populations", "Drug effects on the body", "Individual patient physiology"], answer: 1 },
  { text: "The defence mechanism in which unacceptable feelings are attributed to others is:", options: ["Repression", "Regression", "Projection", "Rationalisation"], answer: 2 },
  { text: "The HIGHEST risk factor associated with completed suicide is:", options: ["Unemployment", "Previous suicide attempt", "Living alone", "Mild depressive episode"], answer: 1 },
  { text: "Electroconvulsive Therapy (ECT) is indicated in:", options: ["Schizophrenia without depression", "Severe treatment-resistant depression", "Generalised anxiety disorder", "Personality disorder"], answer: 1 },
  { text: "A common extrapyramidal side effect of long-term antipsychotic medication is:", options: ["Hypotension", "Tardive dyskinesia", "Weight loss", "Insomnia"], answer: 1 },
  { text: "A patient on a psychiatric ward becomes agitated and attempts to elope. The nurse's FIRST action is:", options: ["Restrain the patient immediately", "Call security first", "Use therapeutic communication to de-escalate", "Administer a sedative without discussion"], answer: 2 },
  { text: "Mental Status Examination (MSE) includes assessment of:", options: ["Renal function only", "Appearance, behaviour, speech, mood, thought, cognition and insight", "Neurological reflexes only", "Blood pressure and pulse"], answer: 1 },
  { text: "Which of the following is a POSITIVE symptom of schizophrenia?", options: ["Flat affect", "Alogia (poverty of speech)", "Hallucinations", "Avolition"], answer: 2 },
  { text: "Which of the following is an example of PRIMARY prevention?", options: ["Chemotherapy for cancer", "Rehabilitation after stroke", "Immunisation against hepatitis B", "Dialysis for renal failure"], answer: 2 },
  { text: "Herd immunity is achieved when:", options: ["All members of a community are vaccinated", "A sufficient proportion of the population is immune, reducing disease transmission", "Only children are vaccinated", "Natural immunity develops after an epidemic"], answer: 1 },
  { text: "The school health programme objective includes:", options: ["Treating only communicable diseases", "Health promotion, screening and early intervention in school-age children", "Providing tertiary care in schools", "Replacing primary health centres"], answer: 1 },
  { text: "The structure of the eye that regulates the amount of light entering is:", options: ["Pupil", "Lens", "Retina", "Sclera"], answer: 0 },
  { text: "Taste buds are mainly present on the:", options: ["Tongue", "Pharynx", "Larynx", "Nasal septum"], answer: 0 },
  { text: "The receptor cells for smell are located in the:", options: ["Olfactory epithelium", "Eustachian tube", "Ciliary body", "Semicircular canal"], answer: 0 },
  { text: "National Health Mission (NHM) was launched in India in:", options: ["2000", "2005", "2013", "2017"], answer: 2 },
  { text: "MCH (Maternal and Child Health) services are primarily delivered at:", options: ["National referral hospital", "Sub-centre and PHC level", "District hospital level only", "Private hospital level"], answer: 1 },

  // ── Section E — GK & Aptitude (Q81–Q100) ──
  { text: "Photoreceptors of the retina include:", options: ["Rods and cones", "Ossicles", "Papillae", "Maculae"], answer: 0 },
  { text: "The white outer protective coat of the eyeball is:", options: ["Retina", "Sclera", "Lens", "Conjunctiva"], answer: 1 },
  { text: "The part of the inner ear responsible for equilibrium and balance is:", options: ["Cochlea", "Vestibular apparatus (semicircular canals)", "Tympanic membrane", "Malleus"], answer: 1 },
  { text: "AIIMS (All India Institute of Medical Sciences), New Delhi was established in:", options: ["1947", "1952", "1956", "1960"], answer: 2 },
  { text: "World Health Day is observed on:", options: ["1 January", "7 April", "14 November", "12 August"], answer: 1 },
  { text: "Florence Nightingale was born in the year:", options: ["1800", "1820", "1835", "1850"], answer: 1 },
  { text: "ICMR stands for:", options: ["Indian Council of Medical Research", "International Council of Medical Records", "Indian Commission of Medical Registration", "Integrated Council of Medical Reform"], answer: 0 },
  { text: "National Nurses Day in India is celebrated on:", options: ["12 May", "12 August", "6 April", "7 April"], answer: 0 },
  { text: "If a nurse works 8 hours/day for 5 days/week, total hours worked in 4 weeks is:", options: ["120 hours", "160 hours", "140 hours", "180 hours"], answer: 1 },
  { text: "A ward has 30 patients. If 40% need wound dressing, how many patients need it?", options: ["10", "12", "15", "18"], answer: 1 },
  { text: "A doctor prescribes 500 mg of a drug. Available tablets are 250 mg each. How many tablets should the nurse administer?", options: ["1", "1.5", "2", "3"], answer: 2 },
  { text: "IV fluid runs at 60 drops/min with a drop factor of 20 drops/mL. Volume infused in 1 hour is:", options: ["100 mL", "120 mL", "180 mL", "200 mL"], answer: 2 },
  { text: "The cost of one pair of gloves is ₹25. If a ward orders 8 pairs daily, the monthly cost (30 days) is:", options: ["₹4,000", "₹5,000", "₹6,000", "₹6,500"], answer: 2 },
  { text: "Which Article of the Indian Constitution guarantees the Right to Equality?", options: ["Article 14", "Article 19", "Article 21", "Article 32"], answer: 0 },
  { text: "Rajya Sabha (Council of States) can have a maximum of how many members?", options: ["250", "245", "238", "300"], answer: 0 },
  { text: "Which organisation publishes the International Classification of Diseases (ICD)?", options: ["UNICEF", "WHO (World Health Organisation)", "AIIMS", "Indian Nursing Council"], answer: 1 },
  { text: "The Indian Nursing Council Act was enacted in:", options: ["1934", "1947", "1952", "1960"], answer: 1 },
  { text: "A patient's temperature is 104°F. In Celsius, this equals:", options: ["38°C", "39°C", "40°C", "41°C"], answer: 2 },
  { text: "The sensitive pigmented vascular layer of the eye situated between the retina and sclera is:", options: ["Cornea", "Retina", "Choroid", "Iris"], answer: 2 },
  { text: "Which of the following best describes the role of the nurse in a multidisciplinary team?", options: ["Following only physician orders", "Coordinating patient care, advocating for the patient and collaborating with all team members", "Performing only technical procedures", "Documenting only"], answer: 1 },
]

export const SECTION_DURATION = 18 * 60 // seconds

export const SECTIONS = [
  { id: 'A', name: 'Nursing Foundations',             fullName: 'Section A — Nursing Foundations',               ids: Array.from({ length: 20 }, (_, i) => i) },
  { id: 'B', name: 'Medical Surgical Nursing',        fullName: 'Section B — Medical Surgical Nursing',           ids: Array.from({ length: 20 }, (_, i) => i + 20) },
  { id: 'C', name: 'Child Health Nursing',             fullName: 'Section C — Child Health Nursing',               ids: Array.from({ length: 20 }, (_, i) => i + 40) },
  { id: 'D', name: 'Community / Mental Health',        fullName: 'Section D — Community Health / Mental Health',   ids: Array.from({ length: 20 }, (_, i) => i + 60) },
  { id: 'E', name: 'GK & Aptitude',                    fullName: 'Section E — GK & Aptitude',                      ids: Array.from({ length: 20 }, (_, i) => i + 80) },
]

export const EXAM_META = {
  name: 'AIIMS NORCET — Nursing Officer Recruitment Common Eligibility Test (Stage I)',
  shortName: 'NORCET 10 — Stage I',
  candidate: 'Anant Trivedi',
  rollNo: '10024156',
  examDate: '13-Jun-2026',
  totalMarks: 100,
  correctMarks: 1,
  wrongMarks: -0.33,
}
