// NORCET 9 Mains — actual previous-year paper (PW), 100 MCQs, purely clinical nursing:
// emergency/critical care, medical-surgical, OBG, paediatrics, psychiatry & community health.
// `answer` is the 0-indexed correct option, taken from the paper's answer key and sanity-
// checked against standard nursing facts (a handful of key OCR/print errors were corrected —
// e.g. Q10 microdrip rate is 250 gtt/min, not the printed 125).
export const MAINS_QUESTIONS = [
  // ── Emergency & critical care ──
  { text: "A nurse performing bag–valve–mask ventilation notices inadequate chest rise. What is the FIRST action?", options: ["Increase oxygen flow", "Reposition the head and mask seal", "Change the mask size", "Begin chest compressions"], answer: 1 },
  { text: "During CPR, the capnography reading suddenly drops to 8 mmHg. This most commonly indicates:", options: ["Hyperventilation", "ROSC", "Poor-quality compressions", "Equipment failure"], answer: 2 },
  { text: "A patient with an ET tube shows sudden absence of the CO₂ waveform. What should the nurse suspect FIRST?", options: ["Pneumothorax", "Tube displacement", "Secretions", "Bronchospasm"], answer: 1 },
  { text: "A trauma patient with suspected spinal injury requires airway opening. Which maneuver?", options: ["Head tilt–chin lift", "Jaw thrust", "Chin lift only", "Triple airway maneuver"], answer: 1 },
  { text: "The correct size of an OPA in an adult is selected by measuring from:", options: ["Nose to navel", "Ear lobe to mouth corner", "Nose to tragus", "Chin to clavicle"], answer: 1 },
  { text: "Most reliable method to confirm tube placement in an intubated patient?", options: ["Bilateral chest movement", "Mist in ET tube", "Continuous waveform capnography", "Auscultation"], answer: 2 },
  { text: "A chest-tube drainage system shows continuous bubbling in the water seal. This means:", options: ["Normal finding", "Air leak", "Blockage", "High suction"], answer: 1 },
  { text: "A patient on a ventilator shows auto-PEEP. What should the nurse do first?", options: ["Increase inspiratory time", "Reduce respiratory rate", "Increase FiO₂", "Administer paralytic"], answer: 1 },
  { text: "Which bag–mask ventilation technique is MOST effective for one rescuer?", options: ["EC technique", "Two-hand seal", "One-hand seal", "C-clamp technique"], answer: 0 },
  { text: "A patient is receiving 500 mL NS over 2 hours with a microdrip set (60 gtt/mL). Drip rate?", options: ["150 gtt/min", "250 gtt/min", "125 gtt/min", "200 gtt/min"], answer: 1 },
  { text: "Which electrolyte imbalance increases the risk of digoxin toxicity?", options: ["Hyperkalemia", "Hypokalemia", "Hypercalcemia", "Hyponatremia"], answer: 1 },
  { text: "Sudden tracheal deviation to the left indicates:", options: ["Left pleural effusion", "Right tension pneumothorax", "Gastric distension", "Cardiac tamponade"], answer: 1 },
  { text: "Post-intubation, absent breath sound on the left side indicates:", options: ["Pleural effusion", "Right mainstem intubation", "Pneumomediastinum", "Pulmonary edema"], answer: 1 },
  { text: "In massive hemorrhage, the best IV fluid initially is:", options: ["5% dextrose", "Ringer's lactate", "0.45% NS", "Distilled water"], answer: 1 },
  { text: "The most common complication of NPA insertion is:", options: ["Nasal bleeding", "Vomiting", "Laryngospasm", "Trismus"], answer: 0 },
  { text: "Which sign indicates worsening shock?", options: ["Warm skin", "Increasing pulse pressure", "Decreasing urine output", "Bounding pulse"], answer: 2 },
  { text: "Most effective position for a patient with air embolism?", options: ["Supine", "Left lateral + Trendelenburg", "High Fowler", "Prone"], answer: 1 },
  { text: "In tension pneumothorax, immediate management is:", options: ["Chest tube", "Needle thoracostomy", "BiPAP", "CPAP"], answer: 1 },
  { text: "In a burn patient, signs of airway injury include all EXCEPT:", options: ["Singed nasal hair", "Carbonaceous sputum", "Hoarseness", "Hypertension"], answer: 3 },
  { text: "During BLS, the chest depth for adult CPR is:", options: ["1 inch", "1.5 inches", "2 inches (5 cm)", "3 inches"], answer: 2 },
  { text: "Earliest sign of hypovolemic shock?", options: ["Hypotension", "Tachycardia", "Cyanosis", "Altered sensorium"], answer: 1 },
  { text: "Antidote for benzodiazepine overdose:", options: ["Naloxone", "Flumazenil", "Atropine", "Pralidoxime"], answer: 1 },
  { text: "A patient on warfarin has an INR of 5.6. What to do?", options: ["Continue same dose", "Stop warfarin", "Give full reversal", "Start heparin"], answer: 1 },
  { text: "Hyperthyroidism commonly presents with:", options: ["Bradycardia", "Weight gain", "Heat intolerance", "Constipation"], answer: 2 },
  { text: "Which drug causes ototoxicity?", options: ["Gentamicin", "Amoxicillin", "Ceftriaxone", "Metronidazole"], answer: 0 },
  { text: "A patient with IV phenytoin requires a maximum infusion rate of:", options: ["10 mg/min", "50 mg/min", "100 mg/min", "5 mg/min"], answer: 1 },
  { text: "Peak T waves on ECG indicate:", options: ["Hypokalemia", "Hyperkalemia", "Hypercalcemia", "Hypomagnesemia"], answer: 1 },
  { text: "Heparin acts by enhancing:", options: ["Vitamin K", "Antithrombin III", "Platelets", "Fibrinogen"], answer: 1 },
  { text: "Earliest sign of increasing ICP:", options: ["Seizures", "Confusion", "Irregular pulse", "Hypotension"], answer: 1 },
  { text: "DKA is characterized by all EXCEPT:", options: ["Kussmaul breathing", "Hyperglycemia", "Metabolic alkalosis", "Ketosis"], answer: 2 },
  { text: "Best diagnostic test for pulmonary embolism:", options: ["ECG", "CT pulmonary angiography", "Chest X-ray", "V/Q scan"], answer: 1 },
  { text: "Drug causing lactic acidosis:", options: ["Metformin", "Insulin", "Sitagliptin", "Glipizide"], answer: 0 },
  { text: "Calcium gluconate works by:", options: ["Removing potassium", "Shifting K⁺ intracellularly", "Stabilizing cardiac membrane", "Increasing urine output"], answer: 2 },
  { text: "Most common symptom of anemia:", options: ["Weight gain", "Fatigue", "Constipation", "Polyuria"], answer: 1 },
  { text: "Addison crisis requires:", options: ["Insulin", "Hydrocortisone", "Furosemide", "Atropine"], answer: 1 },
  { text: "Pink frothy sputum indicates:", options: ["Asthma", "Pulmonary embolism", "Pulmonary edema", "Pneumonia"], answer: 2 },
  { text: "Normal CVP range:", options: ["0–2 mmHg", "2–6 mmHg", "10–15 mmHg", "20–25 mmHg"], answer: 1 },
  { text: "Aspirin overdose causes:", options: ["Respiratory alkalosis", "Metabolic alkalosis", "Hypercarbia", "Hypocalcemia"], answer: 0 },
  { text: "Highest TB transmission occurs in:", options: ["Closed crowded rooms", "Open field", "Rainy outdoors", "Well-ventilated hall"], answer: 0 },
  { text: "First sign of hypoxia:", options: ["Cyanosis", "Irritability", "Bradycardia", "Unconsciousness"], answer: 1 },
  // ── Obstetrics & gynaecology ──
  { text: "Best position during cord prolapse:", options: ["Supine", "Knee–chest", "Left lateral", "Lithotomy"], answer: 1 },
  { text: "Earliest sign of pregnancy:", options: ["Ballottement", "Amenorrhea", "Quickening", "Braxton Hicks"], answer: 1 },
  { text: "Oxytocin should be stopped if contractions occur more than:", options: ["Every 5 min", "Every 2 min", "Every 3 min", "Every 10 min"], answer: 1 },
  { text: "Eclampsia seizures are best controlled by:", options: ["Lorazepam", "Magnesium sulfate", "Diazepam", "Phenytoin"], answer: 1 },
  { text: "Lochia serosa appears on:", options: ["Day 1", "Day 3–4", "Day 5–10", "Day 11–14"], answer: 2 },
  { text: "FHR decelerations matching contractions are:", options: ["Late", "Early", "Variable", "Prolonged"], answer: 1 },
  { text: "Earliest sign of placental separation:", options: ["Gush of blood", "Lengthening cord", "Fundus becomes globular", "Pain"], answer: 2 },
  { text: "Gold standard for ectopic pregnancy:", options: ["Urine pregnancy test", "Transvaginal ultrasound", "MRI", "CT scan"], answer: 1 },
  { text: "Best contraception during breastfeeding:", options: ["COC pills", "DMPA", "IUD before 6 weeks", "Emergency pills daily"], answer: 1 },
  { text: "Bishop score assesses:", options: ["Gestational age", "Cervical favorability", "Fetal wellbeing", "Preeclampsia risk"], answer: 1 },
  { text: "APGAR score is recorded at:", options: ["1 and 3 min", "1 and 5 min", "5 and 10 min", "10 and 20 min"], answer: 1 },
  { text: "Commonest site of ectopic pregnancy:", options: ["Ampulla", "Isthmus", "Cervix", "Ovary"], answer: 0 },
  { text: "Most common cause of postpartum hemorrhage:", options: ["Retained placenta", "Uterine atony", "Trauma", "Coagulation disorders"], answer: 1 },
  { text: "Best drug for postpartum uterine atony:", options: ["Misoprostol", "Methylergometrine", "Oxytocin", "Carboprost"], answer: 2 },
  { text: "Fetal position indicated as LOA means:", options: ["Occiput anterior", "Occiput posterior", "Face presentation", "Shoulder presentation"], answer: 0 },
  { text: "True labor pain is:", options: ["Relieved by walking", "Irregular", "Causes cervical changes", "Felt in upper abdomen"], answer: 2 },
  { text: "Maximum risk of neural tube defects occurs due to deficiency of:", options: ["Vit B6", "Vit C", "Folic acid", "Niacin"], answer: 2 },
  { text: "Tocolytics are used to:", options: ["Delay labor", "Induce labor", "Increase FHR", "Stop contractions post-delivery"], answer: 0 },
  { text: "Maternal diabetes leads to:", options: ["Small baby", "Macrosomia", "Preterm baby only", "Anemia"], answer: 1 },
  { text: "Best method to detect fetal anemia:", options: ["CTG", "Doppler MCA", "Amniocentesis", "NST"], answer: 1 },
  // ── Paediatrics ──
  { text: "Earliest reflex lost in the newborn:", options: ["Moro", "Rooting", "Palmar grasp", "Tonic neck"], answer: 1 },
  { text: "The vaccine given at birth EXCEPT:", options: ["OPV", "BCG", "Hepatitis B", "DPT"], answer: 3 },
  { text: "Vitamin K dose for the newborn:", options: ["0.1 mg", "1 mg IM", "5 mg IM", "10 mg IM"], answer: 1 },
  { text: "Croup presents with:", options: ["Barking cough", "Productive cough", "Wheezing", "Cyanosis only"], answer: 0 },
  { text: "Best indicator of dehydration in infants:", options: ["Weight loss", "Skin turgor", "Tears absent", "Dry mouth"], answer: 0 },
  { text: "Commonest cause of neonatal sepsis:", options: ["Staph", "E. coli", "Pseudomonas", "Klebsiella"], answer: 1 },
  { text: "Congenital hypothyroidism presents with:", options: ["Diarrhea", "Prolonged jaundice", "Tachycardia", "Early closure of fontanelle"], answer: 1 },
  { text: "ORS osmolarity recommended by WHO:", options: ["411 mOsm/L", "310 mOsm/L", "245 mOsm/L", "600 mOsm/L"], answer: 2 },
  { text: "Vaccine causing intussusception risk:", options: ["BCG", "Rotavirus", "MMR", "Hep A"], answer: 1 },
  { text: "Breast milk is deficient in:", options: ["Vit K", "Vit C", "Fat", "Lactose"], answer: 0 },
  // ── Psychiatry ──
  { text: "Flight of ideas is seen in:", options: ["Depression", "Mania", "OCD", "Catatonia"], answer: 1 },
  { text: "Thought blocking means:", options: ["Fast thinking", "Sudden stop in thinking", "Repetitive thoughts", "Irrelevant speech"], answer: 1 },
  { text: "Drug causing agranulocytosis:", options: ["Clozapine", "Haloperidol", "Fluoxetine", "Lorazepam"], answer: 0 },
  { text: "Negative symptoms include all EXCEPT:", options: ["Avolition", "Alogia", "Hallucination", "Anhedonia"], answer: 2 },
  { text: "Best first-line drug for OCD:", options: ["Haloperidol", "SSRI", "Lithium", "Risperidone"], answer: 1 },
  { text: "Alcohol withdrawal presents first with:", options: ["Tremors", "Seizures", "Hallucinations", "Delirium tremens"], answer: 0 },
  { text: "Autism shows deficit in:", options: ["Attention", "Social interaction", "Intelligence", "Motor strength"], answer: 1 },
  { text: "Main defense mechanism in OCD:", options: ["Denial", "Projection", "Undoing", "Sublimation"], answer: 2 },
  { text: "Waxy flexibility is a sign of:", options: ["Catatonia", "Mania", "Depression", "Anxiety"], answer: 0 },
  { text: "Lithium toxicity earliest sign:", options: ["Ataxia", "Diarrhea", "Seizure", "Coma"], answer: 1 },
  // ── Community health & fundamentals ──
  { text: "Incidence measures:", options: ["New cases", "Existing cases", "Deaths", "Cure rate"], answer: 0 },
  { text: "Herd immunity protects:", options: ["Only immune people", "Entire community", "Only vaccinated", "Only newborns"], answer: 1 },
  { text: "Example of primary prevention:", options: ["Screening", "Rehabilitation", "Vaccination", "Surgery"], answer: 2 },
  { text: "Under JSY, benefit focuses on:", options: ["Anemia", "Safe institutional delivery", "Immunization", "PNC care"], answer: 1 },
  { text: "RNTCP aims to eliminate TB by year:", options: ["2020", "2025", "2030", "2050"], answer: 1 },
  { text: "A screening test should have high:", options: ["Specificity", "Sensitivity", "Predictive value", "Accuracy only"], answer: 1 },
  { text: "Most sensitive indicator of community nutrition:", options: ["Under-5 mortality", "Neonatal mortality", "Infant mortality", "Maternal mortality"], answer: 2 },
  { text: "Lead in water causes:", options: ["Neuromuscular weakness", "Hypertension", "Nephritis", "Anemia + neurotoxicity"], answer: 3 },
  { text: "Best method for simple random sampling:", options: ["Select nearest people", "Pick names from lottery", "Choose by age", "Choose volunteers"], answer: 1 },
  { text: "Breastfeeding should be started within:", options: ["1 hour", "6 hours", "12 hours", "24 hours"], answer: 0 },
  { text: "Normal CSF glucose (mg/dL):", options: ["10–20", "20–40", "40–70", "80–120"], answer: 2 },
  { text: "Most radiosensitive cell:", options: ["Neuron", "Lymphocyte", "Muscle", "Bone"], answer: 1 },
  { text: "Transmission of measles:", options: ["Water", "Airborne", "Fomite", "Vector"], answer: 1 },
  { text: "Rh incompatibility occurs in:", options: ["Rh+ mother, Rh− baby", "Rh− mother, Rh+ baby", "Both Rh+", "Both Rh−"], answer: 1 },
  { text: "Vitamin D deficiency causes:", options: ["Scurvy", "Rickets", "Night blindness", "Beriberi"], answer: 1 },
  { text: "Most reliable indicator of fetal well-being:", options: ["FMF", "NST", "BPP", "CTG"], answer: 2 },
  { text: "Puerperium lasts for:", options: ["2 weeks", "4 weeks", "6 weeks", "12 weeks"], answer: 2 },
  { text: "Lactational amenorrhea is effective up to:", options: ["3 months", "6 months", "9 months", "1 year"], answer: 1 },
  { text: "Most common cause of neonatal death:", options: ["Infection", "Prematurity", "Asphyxia", "Congenital anomaly"], answer: 1 },
  { text: "Normal amniotic fluid at term:", options: ["300 mL", "500 mL", "800 mL", "1500 mL"], answer: 2 },
]
